export const restaurantQuestionsSpareCapacity = {
    "Fast Food Restaurant": [
        "What are your least busy hours of the day?", 
        "What are your lowest-performing days of the week?", 
        "How do weather conditions impact customer traffic?" , 
        "Do your breakfast, lunch, or dinner rushes have gaps in between? " ,
        "What percentage of your seating remains unoccupied during non-peak hours? " ,
        "Do you experience a significant drop in sales between meal periods? " ,
        "Are there specific menu items that sell poorly at certain times? " ,
        "Have you considered special pricing during off-peak hours? " ,
        "How effective are your promotions in attracting customers during slow periods?  " ,
        "Does your drive-thru perform better than dine-in during slow hours? " ,
       " How do local school or business schedules impact your sales? " ,
        "Do you offer discounts or bundle deals to increase sales during quiet times?  " ,
        "Are your staffing levels optimized for fluctuations in demand? " , 
        "Have you considered offering a late-night or early morning menu to increase traffic? " ,
        "What role does online delivery play in offsetting low in-store traffic?  " ,
        "How often do you have excess unsold inventory at the end of the day? " ,
        "Do competitor promotions affect your traffic during slow periods? " ,
        "Have you explored targeted marketing to drive footfall during slow hours?", 
        "Could adjusting operational hours reduce costs during extremely slow periods?",  
        "Have you considered partnerships with local businesses to boost off-peak sales? "
    ],
    "Fine Dining Restaurant": [
        "Which days of the week have the lowest table reservations?  ",  
        "How often do you operate at less than 50% capacity? ", 
        "Do lunch or dinner services have significant gaps in bookings? ", 
        "Are your weekday reservations consistently lower than weekends? ", 
        "What is the average time gap between peak and slow dining periods? ",  
        "Do you experience seasonal fluctuations in reservation patterns? ", 
        "How often are large sections of your restaurant empty during open hours? ",  
        "Are private dining rooms underutilized during specific days or hours? ",  
        "Do last-minute cancellations significantly impact your revenue? ",  
        "Have you implemented an early bird or late-night dining menu to attract customers? ",  
        "Could offering prix fixe or tasting menus during slow times increase sales? ",  
        "Do you see a drop in high-end wine and beverage sales on certain days? ",  
        "Are special events or wine tastings effective in boosting off-peak reservations? ",  
        "Would offering a chef’s table or exclusive experience drive demand during slow periods? ",  
        "Do you market your fine dining experience to corporate or business clients? ",  
        "Could flexible seating arrangements increase table turnover and occupancy? ",  
        "How does your restaurant compete with casual dining or takeout alternatives during slow times? ",  
        "Have you considered partnerships with luxury hotels or travel agencies to increase bookings? ",  
        "Does offering private events or catering services help utilize spare capacity? ",  
        "How effective are social media and email campaigns in filling tables during non-peak hours? "  
    ],
    "Casual Dining Restaurant": [
        "What are your slowest hours of the day?",  
        "Which days of the week see the lowest customer turnout?",  
        "How do holidays and seasonal changes affect your business?",  
        "Are your lunch or dinner rushes followed by significant lulls?",  
        "What is the average table occupancy rate during off-peak hours?",  
        "Do you offer happy hour or special pricing to boost sales in low-demand periods?",  
        "Have you considered adding brunch or late-night service to fill spare capacity?",  
        "How often do you receive large party reservations during weekdays?",  
        "Are your promotions and discounts successfully driving traffic in off-peak times?",  
        "Do online delivery and takeout services compensate for low in-house traffic?",  
        "Are there specific menu items that perform poorly during slower hours?",  
        "Could partnering with local businesses for meal deals increase foot traffic?",  
        "Do staffing levels match customer demand at different times of the day?",  
        "Have you implemented a loyalty program that encourages visits during slow times?",  
        "Could hosting trivia nights, live music, or themed events boost non-peak sales?",  
        "Are your private dining or event spaces underutilized? ",  
        "How often do you have excess food waste due to slow business hours?",  
        "Could a special family meal or kids' promotion bring in more customers during low traffic periods?",  
        "Have you explored cross-promotions with local theaters, gyms, or entertainment venues?",  
        "Would adjusting business hours to match customer traffic trends improve efficiency?"
        
    ],
    "Coffee Shop": [
        "What times of day do you see the fewest customers?",  
        "Which days of the week have the lowest foot traffic?",  
        "Do your morning rush and afternoon lull create spare capacity issues?",  
        "How do weather conditions affect your business?",  
        "Are seasonal drinks and promotions helping to fill slow periods?",  
        "Do you see a drop in dine-in customers due to increasing takeout orders?",  
        "Have you considered introducing a happy hour for coffee and pastries?",  
        "How often do customers leave due to a lack of available seating during peak hours while tables remain empty in off-peak hours?",  
        "Do you offer workspace incentives for remote workers during slow times?",  
        "Would adjusting menu offerings (e.g., sandwiches, light meals) increase lunchtime sales?",  
        "Could loyalty programs or prepaid coffee subscriptions encourage repeat visits?",  
        "Are promotional discounts driving additional revenue, or are they only shifting sales from peak hours?",  
        "Have you considered renting out space for meetings or community events?",  
        "Do you offer delivery or mobile ordering to reach more customers during slow times?",  
        "Have you tested seasonal events (e.g., coffee tastings, latte art workshops) to increase engagement?",  
        "How well do partnerships with local businesses drive additional traffic?",  
        "Could better signage or storefront visibility attract more passersby during off-peak hours?",  
        "Do you optimize staff schedules based on expected customer flow?",  
        "How often do you have excess product waste at the end of the day?", 
        "Have you considered extending business hours for early morning commuters or late-night study groups?" 
    ],
    "Bakery": [
        "What time of day do you experience the slowest sales?",  
        "Which days of the week have the lowest customer traffic?",  
        "Are there specific bakery items that sell poorly during off-peak times?",  
        "How does weather or seasonality impact foot traffic?",  
        "Do you sell perishable items that are often wasted due to slow sales?",  
        "Have you considered offering discounts on day-old or surplus baked goods?",  
        "Do you see more morning or afternoon sales, and how do you balance them?",  
        "Could partnering with local cafés or restaurants help distribute products during slow hours?",  
        "How often do large orders or catering services help fill capacity gaps?",  
        "Would offering baking classes or workshops increase revenue in quiet periods?",  
        "Do you offer delivery options to supplement in-store traffic?",  
        "Have you considered a subscription or membership program for frequent customers?",  
        "Are your online promotions driving sales effectively?",  
        "Do limited-time seasonal offerings help increase sales during slow months?",  
        "Could extending café-style seating encourage more dine-in customers?",  
        "Have you considered cross-promotions with nearby businesses?",  
        "Are your operational hours aligned with peak customer demand?",  
        "Do you offer bulk discounts or family-sized portions to increase sales?",  
        "Could a partnership with grocery stores or supermarkets help sell excess products?", 
        "Have you explored expanding your menu to include light meals or beverages?"  
    ],
    "Seafood Restaurant": [
        "What time of day do you experience the lowest number of diners?",  
        "Which days of the week have the slowest business?",  
        "How do seasonal seafood availability and pricing impact customer traffic?",  
        "Do you experience more reservations on weekends than weekdays?",  
        "What percentage of your dining area remains empty during non-peak hours?",  
        "How often do last-minute cancellations affect table turnover?",  
        "Do certain seafood dishes sell poorly during specific times of the day?",  
        "Have you considered a special seafood tasting menu to attract more diners?",  
        "How effective are happy hour or early bird specials in filling tables?",  
        "Could offering sustainable seafood promotions increase traffic during slow periods?",  
        "Have you considered cross-promotions with wine bars or breweries?",  
        "How do weather conditions affect your sales, especially for outdoor seating?",  
        "Would introducing a takeout or delivery seafood menu improve sales during off-peak hours?",  
        "Are there specific menu items that are wasted due to slow business?",  
        "Could hosting seafood cooking classes or live demonstrations increase engagement?",  
        "Do local events or fishing seasons impact your business?",  
        "Have you considered pre-fixe (fixed price) menus to encourage weekday dining?",  
        "Do you adjust staffing levels based on expected demand?",  
        "Would adding a raw bar or sushi options improve sales in slow times?",  
        "Could partnering with seafood markets or grocery stores boost brand visibility?"   
    ],
    "Vegetarian Restaurant": [
        "What are the slowest hours for your restaurant each day?",  
        "Do you notice lower customer turnout on certain weekdays?",  
        "How do special diets (vegan, gluten-free) impact your menu popularity?",  
        "Do you attract more dine-in or takeout customers?",  
        "Are there seasonal fluctuations in demand for plant-based meals?",  
        "How effective are promotions in increasing foot traffic during slow periods?",  
        "Have you considered loyalty programs to encourage repeat visits?",  
        "Do you offer plant-based meal bundles or family-sized portions?",  
        "How does your restaurant compete with general dining establishments?",  
        "Have you partnered with gyms or wellness centers to attract health-conscious customers?",  
        "Could launching a vegan brunch or happy hour boost sales in off-peak times?",  
        "How often do large catering orders help fill revenue gaps?",  
        "Do you experience high ingredient waste during slow hours?",  
        "Have you considered offering meal-prep kits or frozen options?",  
        "How often do you adjust your menu to introduce seasonal ingredients?",  
        "Would hosting community events or nutrition talks increase customer engagement?",  
        "How does social media impact your weekday weekend traffic?",  
        "Do you offer delivery promotions to boost sales on quiet days?",  
        "Would adjusting operating hours help reduce downtime costs?",  
        "Have you considered a grab-and-go section to increase revenue during low traffic?"
    ],
    "Chinese Cuisine Restaurant": [
        "What are your least busy hours of the day?",  
        "Which days of the week have the lowest customer turnout?",  
        "How do seasonal festivals or holidays affect your restaurant traffic?",  
        "Are there specific dishes that under perform during slow hours?",  
        "Do you offer lunch specials or combo meals to increase midday sales?",  
        "How effective are promotions in bringing in customers on non-peak days?",  
        "Have you explored delivery or online ordering to boost sales?",  
        "How does dine-in vs. takeout business fluctuate across the day?",  
        "Do you experience high food waste due to unused inventory?",  
        "Have you considered hosting cultural events or cooking workshops to drive foot traffic?",  
        "Could a dim sum or hot pot special attract customers in off-peak hours?",  
        "Are your staffing levels optimized to match demand fluctuations?",  
        "Do local businesses order catering for office lunches?",  
        "How often do competitor promotions impact your business?",  
        "Would limited-time regional Chinese cuisine menus improve sales?",  
        "Could partnering with tea shops or Asian supermarkets bring in more customers?",  
        "Do you track customer preferences to adjust menu offerings?",  
        "Would adding late-night or early-morning hours improve business?",  
        "How often do dine-in customers switch to takeout due to long wait times?",  
        "Have you considered loyalty discounts for weekday dining?" 
    ],
    "Pizzeria": [
        "What time of day do you experience the lowest orders?",  
        "Which days of the week have the lowest pizza sales?",  
        "How often are dine-in tables empty while delivery orders are high?",  
        "Do you experience seasonal fluctuations in pizza demand?",  
        "Are lunch specials or combo deals successful in increasing midday sales?",  
        "How effective are loyalty programs in driving repeat customers?",  
        "Do catering or party orders help offset slow business periods?",  
        "How often do you sell excess or unsold pizzas at a discount?",  
        "Would hosting pizza-making classes or themed nights attract more customers?",  
        "Have you considered adding specialty pizzas to increase interest in slow hours?",  
        "How do competing pizzerias or fast-food chains impact your traffic?",  
        "Would offering breakfast or dessert pizzas improve off-peak sales?",  
        "How often do you receive late-night orders compared to daytime sales?",  
        "Do takeout and dine-in sales fluctuate significantly?",  
        "Have you considered bundling pizzas with beverages or appetizers to increase revenue?",  
        "Do you offer discount incentives for larger pizza orders on slow days?",  
        "Would partnering with local breweries or wine shops improve customer engagement?",  
        "Do you track which pizza flavors perform poorly and adjust inventory accordingly?",  
        "Have you considered meal kit versions of your pizza for at-home cooking?",  
        "How often do third-party delivery apps contribute to sales during off-peak hours?"  
    ],
    "Buffet Restaurant": [
        "Which days of the week have the lowest buffet turnout?",  
        "What are the slowest dining hours for your restaurant?",  
        "Do different pricing structures impact customer visits?",  
        "How often do you experience food waste due to low traffic?",  
        "Are there specific buffet items that remain underutilized?",  
        "Have you considered an all-day buffet or limited-time service expansion?",  
        "Do weekday lunch specials improve customer flow?",  
        "Would offering theme nights (e.g., seafood night, BBQ night) attract more diners?",  
        "How do holidays impact buffet attendance?",  
        "Do catering services help optimize food usage during slow times?",  
        "Have you considered a tiered pricing system to attract off-peak visitors?",  
        "Do local events or sports games increase buffet sales?",  
        "Could a takeout or pre-packed meal option boost sales?",  
        "How do customer preferences influence buffet menu changes?",  
        "Are your buffet replenishment schedules optimized for cost savings?",  
        "Do group or family discounts help fill tables during low-traffic times?",  
        "Have you experimented with a pay-by-weight buffet system?",  
        "How effective are social media ads in bringing in more customers?",  
        "Would extending brunch or late-night buffet services improve revenue?",  
        "Have you considered adding a self-service beverage bar to increase profitability?"
        
    ],
    "Bar" : [ 
        "What are your least busy days of the week?",
        "What time of day do you experience the lowest footfall?",
        "Do you see a seasonal drop in customers?",
        "How do special events impact your customer flow?",
        "Do you have slow hours before or after peak times?",
        "Are there specific months where revenue drops?",
        "What factors contribute to lower sales on certain days?",
        "Have you noticed any weather-related trends in customer turnout?",
        "Are your happy hour promotions bringing in enough customers?",
        "Do you have unused tables or bar space during off-peak hours?",
        "How often do customers leave due to long wait times at peak hours while the bar is empty at other times?",
        "Are there specific days when staff are underutilized?",
        "Do you see a drop in customers after major sporting events?",
        "Are your late-night sales lower than expected?",
        "What percentage of your seating capacity remains unoccupied on a typical weekday?",
        "Do you see a significant drop in customers during public holidays?",
        "Have you considered live entertainment or themed nights to boost off-peak traffic?",
        "Are online orders and takeout options available during slow hours?",
        "Do you have loyalty programs targeting off-peak hours?",
        "Would offering limited-time discounts during slow hours help fill spare capacity?"
],
 "Mobile Vendor":[
        "What are your busiest and least busy times of the day?",
        "Are there specific locations where demand is consistently low?",
        "Do weather conditions impact your sales volume?",
        "How do weekdays compare to weekends in terms of sales?",
        "Are there peak seasons for your product, and when are the slow periods?",
        "Do local events help or hinder your sales?",
        "Have you identified areas with fluctuating customer traffic?",
        "What time do you sell the most versus the least?",
        "Have you considered offering different products during low-sales periods?",
        "How does customer demand vary across different locations?",
        "Do you face restrictions on operating hours that affect sales?",
        "Are there missed opportunities in high-footfall areas during certain times?",
        "Do promotions increase sales during off-peak times?",
        "How do competitors manage their slower hours?",
        "Have you explored delivery options to supplement on-site sales?",
        "Are your social media promotions targeting slow hours effectively?",
        "Could partnerships with local businesses help increase demand during slow times?",
        "Have you considered bundling products to increase transaction sizes during slow hours?",
        "Are operational costs sustainable during slow periods?",
        "Would adjusting your location schedule help balance demand across the day?"
],
"Café" :[
        "What time of day do you experience the fewest customers?",
        "Are weekday mornings busier than afternoons?",
        "Do your evening sales drop significantly?",
        "What factors contribute to lower sales at certain times?",
        "How does customer traffic change with the weather?",
        "Do promotions effectively drive customers during slow periods?",
        "Have you considered special offers for off-peak hours?",
        "Is your café space underutilized during quiet hours?",
        "Do customers prefer takeaway over dine-in during certain times?",
        "Have you explored corporate partnerships to drive footfall during slow hours?",
        "Are your peak hours affected by nearby businesses’ opening and closing times?",
        "Would changing operating hours help maximize revenue?",
        "Have you tested limited-time menu items for slower periods?",
        "Could hosting small events or book readings increase traffic in off-peak times?",
        "Are loyalty programs effective in bringing repeat customers during low times?",
        "Have you considered offering workspace solutions for remote workers during quiet hours?",
        "Are there external factors, such as school or work schedules, affecting traffic flow?",
        "Do seasonal changes impact your customer base?",
        "Could extending breakfast hours improve sales in the morning slump?",
        "Would adjusting staffing levels during low-traffic hours reduce costs?"
],
 "Tea House" :[
        "What time of day do you have the lowest number of customers?",
        "Do weekends or weekdays have slower traffic?",
        "How does the weather impact customer visits?",
        "Have you noticed seasonal fluctuations in customer demand?",
        "Are your morning or evening hours underutilized?",
        "Do special promotions during slow hours increase traffic?",
        "What menu items are least popular during off-peak hours?",
        "Have you considered offering limited-time discounts during slower periods?",
        "Could tea-tasting events attract customers during off-peak hours?",
        "Have you explored partnerships with local businesses for cross-promotion?",
        "Would changing your operating hours optimize revenue?",
        "Are your online orders filling in the gaps during quiet hours?",
        "Do customers prefer takeaway over sitting in during slow hours?",
        "Could live music or poetry readings attract customers in low-demand times?",
        "Are certain days consistently slow, and why?",
        "Do competitor promotions impact your traffic during specific hours?",
        "How does foot traffic vary in different weather conditions?",
        "Could adding a lunchtime tea pairing menu boost midday sales?",
        "Have you considered offering a loyalty program for frequent visitors during slow hours?",
        "Would renting out space for small meetings help fill spare capacity?"
],

"Ice Cream Parlour":[
        "What time of year do you experience the lowest sales?",
        "Are there specific days of the week when sales drop?",
        "How do your morning sales compare to afternoon and evening sales?",
        "Do colder weather conditions significantly impact sales?",
        "Are your peak hours only in the evenings, and can this be changed?",
        "Have you considered seasonal promotions for slow months?",
        "Do family-friendly promotions attract more customers during slow hours?",
        "Are there specific flavors that don’t sell well at certain times?",
        "Have you tested special discounts for students or senior citizens during quiet hours?",
        "Would expanding your delivery options help balance demand?",
        "Do you see a drop in sales during school hours?",
        "Would introducing limited-time flavors increase interest during slow periods?",
        "Have you considered loyalty rewards for customers visiting at off-peak times?",
        "Do nearby events impact your sales positively or negatively?",
        "Are customers aware of your special offers during slow hours?",
        "Would adding hot desserts improve sales in colder months?",
        "Have you explored partnerships with local businesses for cross-promotions?",
        "Could adding an ice cream-based breakfast menu increase morning sales?",
        "Would adjusting your operating hours to match local events improve business?",
        "Are there cost-saving measures you could implement during slow times?"
]
  };

export const restaurantQuestionsExcessStock = {
    "Fast Food Restaurant": [
      "Maximum seating capacity",
      "Maximum meals per day",
      "Orders through takeout/delivery",
      "Staff underutilized per shift"
    ],
    "Fine Dining Restaurant": [
      "Maximum reservations per day",
      "Unoccupied seats during peak hours",
      "Storage space unused for inventory",
      "Unused catering/event capacity"
    ],
    "Casual Dining Restaurant": [
      "Maximum seating capacity",
      "Customers served at max capacity",
      "Tables set but not used daily",
      "Hours dining space sits empty"
    ],
    "Coffee Shop": [
      "Beverages served at peak capacity",
      "Orders through takeout/delivery",
      "Prep work outsourced vs. in-house",
      "Storage space unused for inventory"
    ],
    "Bakery": [
      "Maximum meals per day",
      "No. of underutilized delivery vehicles",
      "Reservations no-shows per month",
      "No. of staff underutilized per shift"
    ],
    "Seafood Restaurant": [
      "Maximum seating capacity",
      "No. of tables set but not used daily",
      "Unused catering/event capacity",
      "Kitchen equipment idle during service"
    ],
    "Vegetarian Restaurant": [
      "Maximum reservations per day",
      "No. of outlets",
      "Orders through takeout/delivery",
      "No. of hours dining space empty per day"
    ],
    "Chinese Cuisine Restaurant": [
      "Maximum meals per day",
      "Staff underutilized per shift",
      "Reservations no-shows per month",
      "Storage space unused for inventory"
    ],
    "Pizzeria": [
      "Maximum meals per day",
      "Customers served at max capacity",
      "Kitchen equipment idle during service",
      "Tables set but not used daily"
    ],
    "Buffet Restaurant": [
      "Maximum seating capacity",
      "No. of staff underutilized per shift",
      "Storage space unused for inventory",
      "No. of hours dining space empty per day"
    ]
};

export const restaurantQuestionsRecommendedSolution = {
    "Fast Food Restaurant": [
      "Maximum seating capacity",
      "Maximum meals per day",
      "Orders through takeout/delivery",
      "Staff underutilized per shift"
    ],
    "Fine Dining Restaurant": [
      "Maximum reservations per day",
      "Unoccupied seats during peak hours",
      "Storage space unused for inventory",
      "Unused catering/event capacity"
    ],
    "Casual Dining Restaurant": [
      "Maximum seating capacity",
      "Customers served at max capacity",
      "Tables set but not used daily",
      "Hours dining space sits empty"
    ],
    "Coffee Shop": [
      "Beverages served at peak capacity",
      "Orders through takeout/delivery",
      "Prep work outsourced vs. in-house",
      "Storage space unused for inventory"
    ],
    "Bakery": [
      "Maximum meals per day",
      "No. of underutilized delivery vehicles",
      "Reservations no-shows per month",
      "No. of staff underutilized per shift"
    ],
    "Seafood Restaurant": [
      "Maximum seating capacity",
      "No. of tables set but not used daily",
      "Unused catering/event capacity",
      "Kitchen equipment idle during service"
    ],
    "Vegetarian Restaurant": [
      "Maximum reservations per day",
      "No. of outlets",
      "Orders through takeout/delivery",
      "No. of hours dining space empty per day"
    ],
    "Chinese Cuisine Restaurant": [
      "Maximum meals per day",
      "Staff underutilized per shift",
      "Reservations no-shows per month",
      "Storage space unused for inventory"
    ],
    "Pizzeria": [
      "Maximum meals per day",
      "Customers served at max capacity",
      "Kitchen equipment idle during service",
      "Tables set but not used daily"
    ],
    "Buffet Restaurant": [
      "Maximum seating capacity",
      "No. of staff underutilized per shift",
      "Storage space unused for inventory",
      "No. of hours dining space empty per day"
    ]
};