import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'MCOM WHITE LABEL',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="bg-[#F6F9FC] h-[calc(100dvh-4rem)] w-dvw flex overflow-y-auto justify-around scrollbar-hide">
      {children}
    </div>
  );
}
