import type { Metadata } from 'next';
import { PriceCategoryProvider } from '../components/providers/PriceCategoryProvider';

export const metadata: Metadata = {
  title: 'MCOM BOT PRICING',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <PriceCategoryProvider>
      <div className="bg-[#F6F9FC] h-[calc(100dvh-4rem)] w-dvw flex overflow-y-auto justify-around scrollbar-hide">
        {children}
      </div>
    </PriceCategoryProvider>
  );
}
