import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './components/homepage/feature.css';
import Navbar from './components/Navbar';

const inter = Inter({ variable: '--font-inter', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'MCOM BOT',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <style>{`
          :root {
            --font-inter: ${inter.variable};
          }
        `}</style>
        <body className={`${inter.variable} antialiased`}>
          <Navbar />
          <div className="bg-[#F6F9FC] h-[calc(100dvh-4rem)] w-dvw flex overflow-y-auto justify-around scrollbar-hide">
            {children}
          </div>
        </body>
      </head>
    </html>
  );
}
