export const RetailSpareQuestions = {
  GroupA: [
    {
      "Tittle": "Everyday Essentials & General Retail",
      "Tooltip":
        "Stores that provide daily necessities and general consumer goods",
      "DropDown": [
        {
          "Category": "Supermarkets",
          "Questions": [
            "Type of Retailer",
            "Total retail value of stock",
            "No of Days to completely Restock",
            "How many Restaurant Customers are you and  your team  currently  serving in one hour ?",
            "How many Restaurant Customers are you and  your team Capable of  serving in one hour ?",
            "Current Yearly Turnover",
          ],
        },
        {
          "Category": "Convenience Stores",
          "Questions": [
            "Type of Retailer",
            "Total retail value of stock",
            "No of Days to completely Restock",
            "How many Restaurant Customers are you and  your team  currently  serving in one hour ?",
            "How many Restaurant Customers are you and  your team Capable of  serving in one hour ?",
            "Current Yearly Turnover",
          ],
        },
        { "Category": "Departmental Stores", 
            "Questions": [
                "Type of Retailer",
                "Total retail value of stock",
                "No of Days to completely Restock",
                "How many Restaurant Customers are you and  your team  currently  serving in one hour ?",
                "How many Restaurant Customers are you and  your team Capable of  serving in one hour ?",
                "Current Yearly Turnover",
        ] },
        { "Category": "Food and Drink", 
            "Questions": [
            "Type of Retailer",
            "Total retail value of stock",
            "No of Days to completely Restock",
            "How many Restaurant Customers are you and  your team  currently  serving in one hour ?",
            "How many Restaurant Customers are you and  your team Capable of  serving in one hour ?",
            "Current Yearly Turnover",
        ] },
        { "Category": "Books, Gift, and Stationery", "Questions": [
            "Type of Retailer",
            "Total retail value of stock",
            "No of Days to completely Restock",
            "How many Restaurant Customers are you and  your team  currently  serving in one hour ?",
            "How many Restaurant Customers are you and  your team Capable of  serving in one hour ?",
            "Current Yearly Turnover",
        ] },
        { "Category": "Pharmaceuticals/Health", 
            "Questions": [
            "Type of Retailer",
            "Total retail value of stock",
            "No of Days to completely Restock",
            "How many Restaurant Customers are you and  your team  currently  serving in one hour ?",
            "How many Restaurant Customers are you and  your team Capable of  serving in one hour ?",
            "Current Yearly Turnover",
        ] },
      ],
    },
  ],
  GroupB: [
    {
      "Tittle": "Fashion, Accessories & Lifestyle",
      "Tooltip":
        "Retailers focused on clothing, accessories, and lifestyle products",
      "DropDown": [
        { "Category": "Clothing and Shoes", "Questions": [
            "Type of Retailer",
            "Total retail value of stock",
            "No of Days to completely Restock",
            "How many Restaurant Customers are you and  your team  currently  serving in one hour ?",
            "How many Restaurant Customers are you and  your team Capable of  serving in one hour ?",
            "Current Yearly Turnover",
        ] },
        { "Category": "Watches/Jewelry", "Questions": [
            "Type of Retailer",
            "Total retail value of stock",
            "No of Days to completely Restock",
            "How many Restaurant Customers are you and  your team  currently  serving in one hour ?",
            "How many Restaurant Customers are you and  your team Capable of  serving in one hour ?",
            "Current Yearly Turnover",
        ] },
        { "Category": "Luggage/Accessories", "Questions": [
            "Type of Retailer",
            "Total retail value of stock",
            "No of Days to completely Restock",
            "How many Restaurant Customers are you and  your team  currently  serving in one hour ?",
            "How many Restaurant Customers are you and  your team Capable of  serving in one hour ?",
            "Current Yearly Turnover",
        ] },
        { "Category": "Sports", "Questions": [
            "Type of Retailer",
            "Total retail value of stock",
            "No of Days to completely Restock",
            "How many Restaurant Customers are you and  your team  currently  serving in one hour ?",
            "How many Restaurant Customers are you and  your team Capable of  serving in one hour ?",
            "Current Yearly Turnover",
        ] },
      ],
    },
  ],
  GroupC: [
    {
      "Tittle": "Home, Tech & Specialized Goods",
      "Tooltip":
        "Stores selling home essentials, electronics, and specialty items",
      "DropDown": [
        { "Category": "Furniture and Home", "Questions": [
            "Type of Retailer",
            "Total retail value of stock",
            "No of Days to completely Restock",
            "How many Restaurant Customers are you and  your team  currently  serving in one hour ?",
            "How many Restaurant Customers are you and  your team Capable of  serving in one hour ?",
            "Current Yearly Turnover",
        ] },
        { "Category": "Electrical Goods", "Questions": [
            "Type of Retailer",
            "Total retail value of stock",
            "No of Days to completely Restock",
            "How many Restaurant Customers are you and  your team  currently  serving in one hour ?",
            "How many Restaurant Customers are you and  your team Capable of  serving in one hour ?",
            "Current Yearly Turnover",
        ] },
        { "Category": "DIY", "Questions": [
            "Type of Retailer",
            "Total retail value of stock",
            "No of Days to completely Restock",
            "How many Restaurant Customers are you and  your team  currently  serving in one hour ?",
            "How many Restaurant Customers are you and  your team Capable of  serving in one hour ?",
            "Current Yearly Turnover",
        ] },
        { "Category": "Telephone/Computing", "Questions": [
            "Type of Retailer",
            "Total retail value of stock",
            "No of Days to completely Restock",
            "How many Restaurant Customers are you and  your team  currently  serving in one hour ?",
            "How many Restaurant Customers are you and  your team Capable of  serving in one hour ?",
            "Current Yearly Turnover",
        ] },
        { "Category": "Vehicle/Supplies", "Questions": [
            "Type of Retailer",
            "Total retail value of stock",
            "No of Days to completely Restock",
            "How many Restaurant Customers are you and  your team  currently  serving in one hour ?",
            "How many Restaurant Customers are you and  your team Capable of  serving in one hour ?",
            "Current Yearly Turnover",
        ] },
        { "Category": "Florist/Plants", "Questions": [
            "Type of Retailer",
            "Total retail value of stock",
            "No of Days to completely Restock",
            "How many Restaurant Customers are you and  your team  currently  serving in one hour ?",
            "How many Restaurant Customers are you and  your team Capable of  serving in one hour ?",
            "Current Yearly Turnover",
        ] },
      ],
    },
  ],
  GroupD: [
    {
      "Tittle": "Unique & Specialty Retail",
      "Tooltip": "Retailers catering to specific needs and interests",
      "DropDown": [
        { "Category": "News Agent", "Questions": [
            "Type of Retailer",
            "Total retail value of stock",
            "No of Days to completely Restock",
            "How many Restaurant Customers are you and  your team  currently  serving in one hour ?",
            "How many Restaurant Customers are you and  your team Capable of  serving in one hour ?",
            "Current Yearly Turnover",
        ] },
        { "Category": "Printing and Photography", "Questions": [
            "Type of Retailer",
            "Total retail value of stock",
            "No of Days to completely Restock",
            "How many Restaurant Customers are you and  your team  currently  serving in one hour ?",
            "How many Restaurant Customers are you and  your team Capable of  serving in one hour ?",
            "Current Yearly Turnover",
        ] },
        { "Category": "Charity Shops", "Questions": [
            "Type of Retailer",
            "Total retail value of stock",
            "No of Days to completely Restock",
            "How many Restaurant Customers are you and  your team  currently  serving in one hour ?",
            "How many Restaurant Customers are you and  your team Capable of  serving in one hour ?",
            "Current Yearly Turnover",
        ] },
        { "Category": "Estate Agents", "Questions": [
            "Type of Retailer",
            "Total retail value of stock",
            "No of Days to completely Restock",
            "How many Restaurant Customers are you and  your team  currently  serving in one hour ?",
            "How many Restaurant Customers are you and  your team Capable of  serving in one hour ?",
            "Current Yearly Turnover",
        ] },
        { "Category": "Discount Stores", "Questions": [
            "Type of Retailer",
            "Total retail value of stock",
            "No of Days to completely Restock",
            "How many Restaurant Customers are you and  your team  currently  serving in one hour ?",
            "How many Restaurant Customers are you and  your team Capable of  serving in one hour ?",
            "Current Yearly Turnover",
        ] },
        { "Category": "Online Retailers", "Questions": [
            "Type of Retailer",
            "Total retail value of stock",
            "No of Days to completely Restock",
            "How many Restaurant Customers are you and  your team  currently  serving in one hour ?",
            "How many Restaurant Customers are you and  your team Capable of  serving in one hour ?",
            "Current Yearly Turnover",
        ] },
      ],
    },
  ],
};
