export const serviceProviderSpareQuestions = {
  GroupA: [
    {
      "Tittle": "Entertainment & Lifestyle Services",
      "Tooltip": "Focus on leisure, social, and personal care experiences)",
      "DropDown": [
        {"Category":"Library",
            "Questions": [
                "Average Hourly Call-Out Rate (£)",
                "Total Number of PAYE Staff (including self)",
                "Average Number of Hours Each Person Works Per Day",
                "Average Number of Days a Week Each Person Works",
                "Average Number of Weeks Each Person Works Per Year (max 52)",
                "How many Customers are you, individually, or all the members of your team, currently serving in one hour?",
          ],},
        {"Category":"Cinema",
          "Questions": [
                "Average Hourly Call-Out Rate (£)",
                "Total Number of PAYE Staff (including self)",
                "Average Number of Hours Each Person Works Per Day",
                "Average Number of Days a Week Each Person Works",
                "Average Number of Weeks Each Person Works Per Year (max 52)",
                "How many Customers are you, individually, or all the members of your team, currently serving in one hour?",
          ],  
        },
        {"Category":"Club",
            "Questions": [
                "Average Hourly Call-Out Rate (£)",
                "Total Number of PAYE Staff (including self)",
                "Average Number of Hours Each Person Works Per Day",
                "Average Number of Days a Week Each Person Works",
                "Average Number of Weeks Each Person Works Per Year (max 52)",
                "How many Customers are you, individually, or all the members of your team, currently serving in one hour?",
          ],
        },
        {"Category":"Sport/Recreation Centre",
            "Questions": [
                "Average Hourly Call-Out Rate (£)",
                "Total Number of PAYE Staff (including self)",
                "Average Number of Hours Each Person Works Per Day",
                "Average Number of Days a Week Each Person Works",
                "Average Number of Weeks Each Person Works Per Year (max 52)",
                "How many Customers are you, individually, or all the members of your team, currently serving in one hour?",
          ],
        },
        {"Category":"GYM",
            "Questions": [
                "Average Hourly Call-Out Rate (£)",
                "Total Number of PAYE Staff (including self)",
                "Average Number of Hours Each Person Works Per Day",
                "Average Number of Days a Week Each Person Works",
                "Average Number of Weeks Each Person Works Per Year (max 52)",
                "How many Customers are you, individually, or all the members of your team, currently serving in one hour?",
          ],
        },
        {"Category":"Hair Dresser/Nail Bar",
            "Questions": [
                "Average Hourly Call-Out Rate (£)",
                "Total Number of PAYE Staff (including self)",
                "Average Number of Hours Each Person Works Per Day",
                "Average Number of Days a Week Each Person Works",
                "Average Number of Weeks Each Person Works Per Year (max 52)",
                "How many Customers are you, individually, or all the members of your team, currently serving in one hour?",
          ],
        }
      ],
    },
  ],
  GroupB: [
    {
      "Tittle": "Business & Professional Services",
      "Tooltip":
        "Services that support financial, legal, IT, and broader professional needs",
      "DropDown": [
        {"Category":"Bank / Financial Services (merging Bank, etc.)",
            "Questions": [
                "Average Hourly Call-Out Rate (£)",
                "Total Number of PAYE Staff (including self)",
                "Average Number of Hours Each Person Works Per Day",
                "Average Number of Days a Week Each Person Works",
                "Average Number of Weeks Each Person Works Per Year (max 52)",
                "How many Customers are you, individually, or all the members of your team, currently serving in one hour?",
          ],
        },
        {"Category":"Insurance Services",
            "Questions": [
                "Average Hourly Call-Out Rate (£)",
                "Total Number of PAYE Staff (including self)",
                "Average Number of Hours Each Person Works Per Day",
                "Average Number of Days a Week Each Person Works",
                "Average Number of Weeks Each Person Works Per Year (max 52)",
                "How many Customers are you, individually, or all the members of your team, currently serving in one hour?",
          ],
        },
        {"Category":"IT Services",
            "Questions": [
                "Average Hourly Call-Out Rate (£)",
                "Total Number of PAYE Staff (including self)",
                "Average Number of Hours Each Person Works Per Day",
                "Average Number of Days a Week Each Person Works",
                "Average Number of Weeks Each Person Works Per Year (max 52)",
                "How many Customers are you, individually, or all the members of your team, currently serving in one hour?",
          ],
        },
        {"Category":"Legal Services",
            "Questions": [
                "Average Hourly Call-Out Rate (£)",
                "Total Number of PAYE Staff (including self)",
                "Average Number of Hours Each Person Works Per Day",
                "Average Number of Days a Week Each Person Works",
                "Average Number of Weeks Each Person Works Per Year (max 52)",
                "How many Customers are you, individually, or all the members of your team, currently serving in one hour?",
          ],
        },
        {"Category":"Real Estate Services",
            "Questions": [
                "Average Hourly Call-Out Rate (£)",
                "Total Number of PAYE Staff (including self)",
                "Average Number of Hours Each Person Works Per Day",
                "Average Number of Days a Week Each Person Works",
                "Average Number of Weeks Each Person Works Per Year (max 52)",
                "How many Customers are you, individually, or all the members of your team, currently serving in one hour?",
          ],
        },
        {"Category":"Consulting Services",
            "Questions": [
                "Average Hourly Call-Out Rate (£)",
                "Total Number of PAYE Staff (including self)",
                "Average Number of Hours Each Person Works Per Day",
                "Average Number of Days a Week Each Person Works",
                "Average Number of Weeks Each Person Works Per Year (max 52)",
                "How many Customers are you, individually, or all the members of your team, currently serving in one hour?",
          ],
        },
        {"Category":"Logistics Services",
            "Questions": [
                "Average Hourly Call-Out Rate (£)",
                "Total Number of PAYE Staff (including self)",
                "Average Number of Hours Each Person Works Per Day",
                "Average Number of Days a Week Each Person Works",
                "Average Number of Weeks Each Person Works Per Year (max 52)",
                "How many Customers are you, individually, or all the members of your team, currently serving in one hour?",
          ],
        },
        {"Category":"Travel and Tour Services",
            "Questions": [
                "Average Hourly Call-Out Rate (£)",
                "Total Number of PAYE Staff (including self)",
                "Average Number of Hours Each Person Works Per Day",
                "Average Number of Days a Week Each Person Works",
                "Average Number of Weeks Each Person Works Per Year (max 52)",
                "How many Customers are you, individually, or all the members of your team, currently serving in one hour?",
          ],
        }
      ],
    },
  ],
  GroupC: [
    {
      "Tittle": "Maintenance, Repair & Transport Services",
      "Tooltip": "Providers of repair, maintenance, and hire/transport solutions",
      "DropDown": [
        {"Category":"Car Repairs",
            "Questions": [
                "Average Hourly Call-Out Rate (£)",
                "Total Number of PAYE Staff (including self)",
                "Average Number of Hours Each Person Works Per Day",
                "Average Number of Days a Week Each Person Works",
                "Average Number of Weeks Each Person Works Per Year (max 52)",
                "How many Customers are you, individually, or all the members of your team, currently serving in one hour?",
          ],
        },
        {"Category":"Building/Gardening Services",
            "Questions": [
                "Average Hourly Call-Out Rate (£)",
                "Total Number of PAYE Staff (including self)",
                "Average Number of Hours Each Person Works Per Day",
                "Average Number of Days a Week Each Person Works",
                "Average Number of Weeks Each Person Works Per Year (max 52)",
                "How many Customers are you, individually, or all the members of your team, currently serving in one hour?",
          ],
        },
        {"Category":"Electrical Repair Services",
            "Questions": [
                "Average Hourly Call-Out Rate (£)",
                "Total Number of PAYE Staff (including self)",
                "Average Number of Hours Each Person Works Per Day",
                "Average Number of Days a Week Each Person Works",
                "Average Number of Weeks Each Person Works Per Year (max 52)",
                "How many Customers are you, individually, or all the members of your team, currently serving in one hour?",
          ],
        },
        {"Category":"Cleaning Services",
            "Questions": [
                "Average Hourly Call-Out Rate (£)",
                "Total Number of PAYE Staff (including self)",
                "Average Number of Hours Each Person Works Per Day",
                "Average Number of Days a Week Each Person Works",
                "Average Number of Weeks Each Person Works Per Year (max 52)",
                "How many Customers are you, individually, or all the members of your team, currently serving in one hour?",
          ],
        },
        {"Category":"Plumbing Services",
            "Questions": [
                "Average Hourly Call-Out Rate (£)",
                "Total Number of PAYE Staff (including self)",
                "Average Number of Hours Each Person Works Per Day",
                "Average Number of Days a Week Each Person Works",
                "Average Number of Weeks Each Person Works Per Year (max 52)",
                "How many Customers are you, individually, or all the members of your team, currently serving in one hour?",
          ],
        },
        {"Category":"Catering Services",
            "Questions": [
                "Average Hourly Call-Out Rate (£)",
                "Total Number of PAYE Staff (including self)",
                "Average Number of Hours Each Person Works Per Day",
                "Average Number of Days a Week Each Person Works",
                "Average Number of Weeks Each Person Works Per Year (max 52)",
                "How many Customers are you, individually, or all the members of your team, currently serving in one hour?",
          ],
        },
        {"Category":"Equipment Hire",
            "Questions": [
                "Average Hourly Call-Out Rate (£)",
                "Total Number of PAYE Staff (including self)",
                "Average Number of Hours Each Person Works Per Day",
                "Average Number of Days a Week Each Person Works",
                "Average Number of Weeks Each Person Works Per Year (max 52)",
                "How many Customers are you, individually, or all the members of your team, currently serving in one hour?",
          ],
        },
        {"Category":"Cab Hire",
            "Questions": [
                "Average Hourly Call-Out Rate (£)",
                "Total Number of PAYE Staff (including self)",
                "Average Number of Hours Each Person Works Per Day",
                "Average Number of Days a Week Each Person Works",
                "Average Number of Weeks Each Person Works Per Year (max 52)",
                "How many Customers are you, individually, or all the members of your team, currently serving in one hour?",
          ],
        }
      ],
    },
  ],
  GroupD: [
    {
      "Tittle": "Essential & Community Services",
      "Tooltip": "Services critical to health, education, and public welfare",
      "DropDown": [
        {"Category":"Dentist",
            "Questions": [
                "Average Hourly Call-Out Rate (£)",
                "Total Number of PAYE Staff (including self)",
                "Average Number of Hours Each Person Works Per Day",
                "Average Number of Days a Week Each Person Works",
                "Average Number of Weeks Each Person Works Per Year (max 52)",
                "How many Customers are you, individually, or all the members of your team, currently serving in one hour?",
          ],
        },
        {"Category":"Healthcare Services",
            "Questions": [
                "Average Hourly Call-Out Rate (£)",
                "Total Number of PAYE Staff (including self)",
                "Average Number of Hours Each Person Works Per Day",
                "Average Number of Days a Week Each Person Works",
                "Average Number of Weeks Each Person Works Per Year (max 52)",
                "How many Customers are you, individually, or all the members of your team, currently serving in one hour?",
          ],
        },
        {"Category":"Educational Services",
            "Questions": [
                "Average Hourly Call-Out Rate (£)",
                "Total Number of PAYE Staff (including self)",
                "Average Number of Hours Each Person Works Per Day",
                "Average Number of Days a Week Each Person Works",
                "Average Number of Weeks Each Person Works Per Year (max 52)",
                "How many Customers are you, individually, or all the members of your team, currently serving in one hour?",
          ],
        },
        {"Category":"Post Office",
            "Questions": [
                "Average Hourly Call-Out Rate (£)",
                "Total Number of PAYE Staff (including self)",
                "Average Number of Hours Each Person Works Per Day",
                "Average Number of Days a Week Each Person Works",
                "Average Number of Weeks Each Person Works Per Year (max 52)",
                "How many Customers are you, individually, or all the members of your team, currently serving in one hour?",
          ],
        }
      ],
    },
  ],
};
