export const serviceProviderSpareQuestions = {
  GroupA: [
    {
      "Tittle": "Entertainment & Lifestyle Services",
      "Tooltip": "Focus on leisure, social, and personal care experiences)",
      "DropDown": [
        {"Category":"Library",
            "Questions": [
                "Type of Service Provider",
                "Average Hourly Call Out Rate",
                "Total No.Of PAYE Staff (Including self)",
                "Average No. Of Hours each person works per day",
                "Average No. of Days a week each person works",
                "Average No. of Weeks each person works in a year(Max 52)",
                "How many Customers are  you individually  or all the members  of your team  currently  serving in one hour ?",
                "How many Customers are you individually, or all the members of your team, Capable of  serving in one hour ?",
                "Current Yearly Turnover",
          ],},
        {"Category":"Cinema",
          "Questions": [
                "Type of Service Provider",
                "Average Hourly Call Out Rate",
                "Total No.Of PAYE Staff (Including self)",
                "Average No. Of Hours each person works per day",
                "Average No. of Days a week each person works",
                "Average No. of Weeks each person works in a year(Max 52)",
                "How many Customers are  you individually  or all the members  of your team  currently  serving in one hour ?",
                "How many Customers are you individually, or all the members of your team, Capable of  serving in one hour ?",
                "Current Yearly Turnover",
          ],  
        },
        {"Category":"Club",
            "Questions": [
                "Type of Service Provider",
                "Average Hourly Call Out Rate",
                "Total No.Of PAYE Staff (Including self)",
                "Average No. Of Hours each person works per day",
                "Average No. of Days a week each person works",
                "Average No. of Weeks each person works in a year(Max 52)",
                "How many Customers are  you individually  or all the members  of your team  currently  serving in one hour ?",
                "How many Customers are you individually, or all the members of your team, Capable of  serving in one hour ?",
                "Current Yearly Turnover",
          ],
        },
        {"Category":"Sport/Recreation Centre",
            "Questions": [
                "Type of Service Provider",
                "Average Hourly Call Out Rate",
                "Total No.Of PAYE Staff (Including self)",
                "Average No. Of Hours each person works per day",
                "Average No. of Days a week each person works",
                "Average No. of Weeks each person works in a year(Max 52)",
                "How many Customers are  you individually  or all the members  of your team  currently  serving in one hour ?",
                "How many Customers are you individually, or all the members of your team, Capable of  serving in one hour ?",
                "Current Yearly Turnover",
          ],
        },
        {"Category":"GYM",
            "Questions": [
                "Type of Service Provider",
                "Average Hourly Call Out Rate",
                "Total No.Of PAYE Staff (Including self)",
                "Average No. Of Hours each person works per day",
                "Average No. of Days a week each person works",
                "Average No. of Weeks each person works in a year(Max 52)",
                "How many Customers are  you individually  or all the members  of your team  currently  serving in one hour ?",
                "How many Customers are you individually, or all the members of your team, Capable of  serving in one hour ?",
                "Current Yearly Turnover",
          ],
        },
        {"Category":"Hair Dresser/Nail Bar",
            "Questions": [
                "Type of Service Provider",
                "Average Hourly Call Out Rate",
                "Total No.Of PAYE Staff (Including self)",
                "Average No. Of Hours each person works per day",
                "Average No. of Days a week each person works",
                "Average No. of Weeks each person works in a year(Max 52)",
                "How many Customers are  you individually  or all the members  of your team  currently  serving in one hour ?",
                "How many Customers are you individually, or all the members of your team, Capable of  serving in one hour ?",
                "Current Yearly Turnover",
          ],
        }
      ],
    },
  ],
  GroupB: [
    {
      "Tittle": "Business & Professional Services",
      "Tooltip":
        "Services that support financial, legal, IT, and broader professional needs",
      "DropDown": [
        {"Category":"Bank / Financial Services (merging Bank, etc.)",
            "Questions": [
                "Type of Service Provider",
                "Average Hourly Call Out Rate",
                "Total No.Of PAYE Staff (Including self)",
                "Average No. Of Hours each person works per day",
                "Average No. of Days a week each person works",
                "Average No. of Weeks each person works in a year(Max 52)",
                "How many Customers are  you individually  or all the members  of your team  currently  serving in one hour ?",
                "How many Customers are you individually, or all the members of your team, Capable of  serving in one hour ?",
                "Current Yearly Turnover",
          ],
        },
        {"Category":"Insurance Services",
            "Questions": [
                "Type of Service Provider",
                "Average Hourly Call Out Rate",
                "Total No.Of PAYE Staff (Including self)",
                "Average No. Of Hours each person works per day",
                "Average No. of Days a week each person works",
                "Average No. of Weeks each person works in a year(Max 52)",
                "How many Customers are  you individually  or all the members  of your team  currently  serving in one hour ?",
                "How many Customers are you individually, or all the members of your team, Capable of  serving in one hour ?",
                "Current Yearly Turnover",
          ],
        },
        {"Category":"IT Services",
            "Questions": [
                "Type of Service Provider",
                "Average Hourly Call Out Rate",
                "Total No.Of PAYE Staff (Including self)",
                "Average No. Of Hours each person works per day",
                "Average No. of Days a week each person works",
                "Average No. of Weeks each person works in a year(Max 52)",
                "How many Customers are  you individually  or all the members  of your team  currently  serving in one hour ?",
                "How many Customers are you individually, or all the members of your team, Capable of  serving in one hour ?",
                "Current Yearly Turnover",
          ],
        },
        {"Category":"Legal Services",
            "Questions": [
                "Type of Service Provider",
                "Average Hourly Call Out Rate",
                "Total No.Of PAYE Staff (Including self)",
                "Average No. Of Hours each person works per day",
                "Average No. of Days a week each person works",
                "Average No. of Weeks each person works in a year(Max 52)",
                "How many Customers are  you individually  or all the members  of your team  currently  serving in one hour ?",
                "How many Customers are you individually, or all the members of your team, Capable of  serving in one hour ?",
                "Current Yearly Turnover",
          ],
        },
        {"Category":"Real Estate Services",
            "Questions": [
                "Type of Service Provider",
                "Average Hourly Call Out Rate",
                "Total No.Of PAYE Staff (Including self)",
                "Average No. Of Hours each person works per day",
                "Average No. of Days a week each person works",
                "Average No. of Weeks each person works in a year(Max 52)",
                "How many Customers are  you individually  or all the members  of your team  currently  serving in one hour ?",
                "How many Customers are you individually, or all the members of your team, Capable of  serving in one hour ?",
                "Current Yearly Turnover",
          ],
        },
        {"Category":"Consulting Services",
            "Questions": [
                "Type of Service Provider",
                "Average Hourly Call Out Rate",
                "Total No.Of PAYE Staff (Including self)",
                "Average No. Of Hours each person works per day",
                "Average No. of Days a week each person works",
                "Average No. of Weeks each person works in a year(Max 52)",
                "How many Customers are  you individually  or all the members  of your team  currently  serving in one hour ?",
                "How many Customers are you individually, or all the members of your team, Capable of  serving in one hour ?",
                "Current Yearly Turnover",
          ],
        },
        {"Category":"Logistics Services",
            "Questions": [
                "Type of Service Provider",
                "Average Hourly Call Out Rate",
                "Total No.Of PAYE Staff (Including self)",
                "Average No. Of Hours each person works per day",
                "Average No. of Days a week each person works",
                "Average No. of Weeks each person works in a year(Max 52)",
                "How many Customers are  you individually  or all the members  of your team  currently  serving in one hour ?",
                "How many Customers are you individually, or all the members of your team, Capable of  serving in one hour ?",
                "Current Yearly Turnover",
          ],
        },
        {"Category":"Travel and Tour Services",
            "Questions": [
                "Type of Service Provider",
                "Average Hourly Call Out Rate",
                "Total No.Of PAYE Staff (Including self)",
                "Average No. Of Hours each person works per day",
                "Average No. of Days a week each person works",
                "Average No. of Weeks each person works in a year(Max 52)",
                "How many Customers are  you individually  or all the members  of your team  currently  serving in one hour ?",
                "How many Customers are you individually, or all the members of your team, Capable of  serving in one hour ?",
                "Current Yearly Turnover",
          ],
        }
      ],
    },
  ],
  GroupC: [
    {
      "Tittle": "Maintenance, Repair & Transport Services",
      "Tooltip": "Providers of repair, maintenance, and hire/transport solutions",
      "DropDown": [
        {"Category":"Car Repairs",
            "Questions": [
                "Type of Service Provider",
                "Average Hourly Call Out Rate",
                "Total No.Of PAYE Staff (Including self)",
                "Average No. Of Hours each person works per day",
                "Average No. of Days a week each person works",
                "Average No. of Weeks each person works in a year(Max 52)",
                "How many Customers are  you individually  or all the members  of your team  currently  serving in one hour ?",
                "How many Customers are you individually, or all the members of your team, Capable of  serving in one hour ?",
                "Current Yearly Turnover",
          ],
        },
        {"Category":"Building/Gardening Services",
            "Questions": [
                "Type of Service Provider",
                "Average Hourly Call Out Rate",
                "Total No.Of PAYE Staff (Including self)",
                "Average No. Of Hours each person works per day",
                "Average No. of Days a week each person works",
                "Average No. of Weeks each person works in a year(Max 52)",
                "How many Customers are  you individually  or all the members  of your team  currently  serving in one hour ?",
                "How many Customers are you individually, or all the members of your team, Capable of  serving in one hour ?",
                "Current Yearly Turnover",
          ],
        },
        {"Category":"Electrical Repair Services",
            "Questions": [
                "Type of Service Provider",
                "Average Hourly Call Out Rate",
                "Total No.Of PAYE Staff (Including self)",
                "Average No. Of Hours each person works per day",
                "Average No. of Days a week each person works",
                "Average No. of Weeks each person works in a year(Max 52)",
                "How many Customers are  you individually  or all the members  of your team  currently  serving in one hour ?",
                "How many Customers are you individually, or all the members of your team, Capable of  serving in one hour ?",
                "Current Yearly Turnover",
          ],
        },
        {"Category":"Cleaning Services",
            "Questions": [
                "Type of Service Provider",
                "Average Hourly Call Out Rate",
                "Total No.Of PAYE Staff (Including self)",
                "Average No. Of Hours each person works per day",
                "Average No. of Days a week each person works",
                "Average No. of Weeks each person works in a year(Max 52)",
                "How many Customers are  you individually  or all the members  of your team  currently  serving in one hour ?",
                "How many Customers are you individually, or all the members of your team, Capable of  serving in one hour ?",
                "Current Yearly Turnover",
          ],
        },
        {"Category":"Plumbing Services",
            "Questions": [
                "Type of Service Provider",
                "Average Hourly Call Out Rate",
                "Total No.Of PAYE Staff (Including self)",
                "Average No. Of Hours each person works per day",
                "Average No. of Days a week each person works",
                "Average No. of Weeks each person works in a year(Max 52)",
                "How many Customers are  you individually  or all the members  of your team  currently  serving in one hour ?",
                "How many Customers are you individually, or all the members of your team, Capable of  serving in one hour ?",
                "Current Yearly Turnover",
          ],
        },
        {"Category":"Catering Services",
            "Questions": [
                "Type of Service Provider",
                "Average Hourly Call Out Rate",
                "Total No.Of PAYE Staff (Including self)",
                "Average No. Of Hours each person works per day",
                "Average No. of Days a week each person works",
                "Average No. of Weeks each person works in a year(Max 52)",
                "How many Customers are  you individually  or all the members  of your team  currently  serving in one hour ?",
                "How many Customers are you individually, or all the members of your team, Capable of  serving in one hour ?",
                "Current Yearly Turnover",
          ],
        },
        {"Category":"Equipment Hire",
            "Questions": [
                "Type of Service Provider",
                "Average Hourly Call Out Rate",
                "Total No.Of PAYE Staff (Including self)",
                "Average No. Of Hours each person works per day",
                "Average No. of Days a week each person works",
                "Average No. of Weeks each person works in a year(Max 52)",
                "How many Customers are  you individually  or all the members  of your team  currently  serving in one hour ?",
                "How many Customers are you individually, or all the members of your team, Capable of  serving in one hour ?",
                "Current Yearly Turnover",
          ],
        },
        {"Category":"Cab Hire",
            "Questions": [
                "Type of Service Provider",
                "Average Hourly Call Out Rate",
                "Total No.Of PAYE Staff (Including self)",
                "Average No. Of Hours each person works per day",
                "Average No. of Days a week each person works",
                "Average No. of Weeks each person works in a year(Max 52)",
                "How many Customers are  you individually  or all the members  of your team  currently  serving in one hour ?",
                "How many Customers are you individually, or all the members of your team, Capable of  serving in one hour ?",
                "Current Yearly Turnover",
          ],
        }
      ],
    },
  ],
  GroupD: [
    {
      "Tittle": "Essential & Community Services",
      "Tooltip": "Services critical to health, education, and public welfare",
      "DropDown": [
        {"Category":"Dentist",
            "Questions": [
                "Type of Service Provider",
                "Average Hourly Call Out Rate",
                "Total No.Of PAYE Staff (Including self)",
                "Average No. Of Hours each person works per day",
                "Average No. of Days a week each person works",
                "Average No. of Weeks each person works in a year(Max 52)",
                "How many Customers are  you individually  or all the members  of your team  currently  serving in one hour ?",
                "How many Customers are you individually, or all the members of your team, Capable of  serving in one hour ?",
                "Current Yearly Turnover",
          ],
        },
        {"Category":"Healthcare Services",
            "Questions": [
                "Type of Service Provider",
                "Average Hourly Call Out Rate",
                "Total No.Of PAYE Staff (Including self)",
                "Average No. Of Hours each person works per day",
                "Average No. of Days a week each person works",
                "Average No. of Weeks each person works in a year(Max 52)",
                "How many Customers are  you individually  or all the members  of your team  currently  serving in one hour ?",
                "How many Customers are you individually, or all the members of your team, Capable of  serving in one hour ?",
                "Current Yearly Turnover",
          ],
        },
        {"Category":"Educational Services",
            "Questions": [
                "Type of Service Provider",
                "Average Hourly Call Out Rate",
                "Total No.Of PAYE Staff (Including self)",
                "Average No. Of Hours each person works per day",
                "Average No. of Days a week each person works",
                "Average No. of Weeks each person works in a year(Max 52)",
                "How many Customers are  you individually  or all the members  of your team  currently  serving in one hour ?",
                "How many Customers are you individually, or all the members of your team, Capable of  serving in one hour ?",
                "Current Yearly Turnover",
          ],
        },
        {"Category":"Post Office",
            "Questions": [
                "Type of Service Provider",
                "Average Hourly Call Out Rate",
                "Total No.Of PAYE Staff (Including self)",
                "Average No. Of Hours each person works per day",
                "Average No. of Days a week each person works",
                "Average No. of Weeks each person works in a year(Max 52)",
                "How many Customers are  you individually  or all the members  of your team  currently  serving in one hour ?",
                "How many Customers are you individually, or all the members of your team, Capable of  serving in one hour ?",
                "Current Yearly Turnover",
          ],
        }
      ],
    },
  ],
};
